public:
    workarea: ".worklib"
    reference: "V01.00"
    projects:
      - repourl: "git@gitlab.com:projtemplates/go.git"
        reference: "master"
        path: "go/lib"
        build: "make setup all"
private:
    workarea: ".work"
    server: "git@gitlab.com:"
    reference: "tagx02"
    projects:
      - repo: "RajaSrinivasan/icm.git"
        path: "icm"
        reference: "V01.06"
      - repo: "RajaSrinivasan/codex.git"
        path: "codex"
        reference: "v0.1.0-B"
        build: "make setup all test"
      - repourl: "https://github.com/RajaSrinivasan/srctrace.git"
        path: "srct"
      - repourl: "git@github.com:repotrace.git"
        path: "repot"
