public:
    workarea: ".worklib"
    reference: "V01.00"
    projects:
      - repourl: "git@gitlab.com:projtemplates/go.git"
        reference: "master"
        path: "go/lib"
        build: "make setup all"
private:
    workarea: ".work"
    server: "git@gitlab.com:"
    reference: "tagx02"
    projects:
      - repo: "RajaSrinivasan/icm.git"
        path: "icm"
        reference: "V01.06"
      - repo: "RajaSrinivasan/codex.git"
        path: "codex"
        reference: "development"
        build: "make setup all"
      - repourl: "https://github.com/RajaSrinivasan/srctrace.git"
        path: "tools/srctrace"
      - repourl: "git@github.com:repotrace.git"
        path: "tools/repotrace"
